export const variants = [
  ["01", "The Dossier"], ["02", "Front Page"], ["03", "Case File"], ["04", "Long Read"], ["05", "Red Line"],
  ["06", "Field Manual"], ["07", "The Record"], ["08", "Split Verdict"], ["09", "Dispatch"], ["10", "Evidence Wall"],
] as const;

export const sections = [
  { title: "What the Convention actually decides", text: "A Hague return case is generally not a custody trial. The court is usually deciding whether a child was wrongfully removed from, or retained outside, the child’s country of habitual residence—and, if so, whether the child should be returned so custody can be decided there. That distinction changes everything. A parent can have powerful custody arguments and still lose focus if those arguments do not answer the return question before the court." },
  { title: "The questions that shape the case", text: "The analysis commonly turns on the child’s habitual residence immediately before the alleged removal or retention, whether the left-behind parent held and was actually exercising custody rights, and whether the removal breached those rights. Dates, travel permissions, school records, messages, parenting routines, immigration documents, and prior agreements may all become part of the factual record." },
  { title: "Why speed and discipline matter", text: "The Convention is built around prompt proceedings. Delay can change the practical and legal landscape, especially after a child has been in the new country for a year. Early action is not the same as frantic action. Preserve evidence, build a reliable chronology, understand the forum, and speak with qualified counsel before sending emotional messages that may later be read in court." },
  { title: "Defenses are narrow—not casual escape hatches", text: "The Convention recognizes limited exceptions, including consent or acquiescence, grave risk of harm, a mature child’s objection, and—in some cases—settlement after more than one year. Courts often construe these exceptions carefully because the proceeding is designed to determine forum, not to reward unilateral relocation. Their availability depends on specific facts and governing law." },
  { title: "Build the record before you build the argument", text: "Start with a dated timeline that separates what you know from what you assume. Preserve original messages and metadata. Identify neutral witnesses. Gather documents showing where the child lived, went to school, received medical care, and participated in community life. Record the parenting arrangement and any travel consent precisely. Credibility is an asset; exaggeration spends it." },
  { title: "The father’s task", text: "International family litigation invites panic, rage, and public performance. None of those substitutes for a clean record. Your job is to remain present, document reality, protect the child from the conflict where possible, and make each decision as though it will be projected on a courtroom wall. The strongest posture is not passivity. It is controlled force." },
] as const;
