import { notFound } from "next/navigation";
import Link from "next/link";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

const pages: Record<string, { eyebrow: string; title: string; intro: string; type: string }> = {
  podcast: { eyebrow: "Podcast · Coming soon", title: "Conversations for men who refuse to disappear.", intro: "Long-form conversations on fatherhood, family court, business, love, sovereignty, and the systems shaping modern men.", type: "podcast" },
  books: { eyebrow: "Books", title: "The story. The strategy.", intro: "Two books born from the same fight: one memoir and one practical guide to protecting your bloodline.", type: "books" },
  speaking: { eyebrow: "Speaking", title: "A voice forged in the fight.", intro: "Steve speaks on fatherhood, family systems, leadership under pressure, and building what survives the battle.", type: "speaking" },
  apparel: { eyebrow: "Apparel · Coming soon", title: "Wear the bloodline.", intro: "A restrained collection for the men who carry the standard. The first drop is being forged.", type: "apparel" },
  about: { eyebrow: "Steve Love", title: "The man behind the front.", intro: "Author, father, entrepreneur, strategist, and litigator—built through exile, family court, business, and the refusal to disappear.", type: "about" },
};

export function generateStaticParams() {
  return Object.keys(pages).map((slug) => ({ slug }));
}

function PageContent({ type }: { type: string }) {
  if (type === "books") return <div className="inner-grid books-list"><article><img src="/assets/stolen-sons.png" alt="Stolen Sons" /><div><span>Memoir</span><h2>Stolen Sons</h2><p>A father erased. A son taken. A fight not finished.</p><Link className="button ink" href="/stolen-sons">Explore the book</Link></div></article><article><img src="/assets/family-lawfare.png" alt="Family Lawfare" /><div><span>Field guide</span><h2>Family Lawfare</h2><p>Protect your bloodline, rights, and legacy when the courts enter your family.</p><Link className="button ink" href="/family-lawfare">Explore the book</Link></div></article></div>;
  if (type === "work") return <div className="work-with-page">
    <section className="work-opening"><p className="section-kicker">The work</p><h2>Every battle crosses<br /><em>more than one front.</em></h2><p>We work across Leadership, Legacy, Law, and Love because a decision made on one front creates consequences across the others.</p></section>
    <section className="transformation"><div className="transformation-head"><p className="section-kicker">The four-front transformation</p><div><span>Before</span><span>After</span></div></div>
      <article><header><b>01</b><h3>Leadership</h3></header><p>Your private battles consume your attention, weaken your decisions, and follow you into the business.</p><i>→</i><p>You lead your team, revenue, and growth with clarity—even when life outside the business is under pressure.</p></article>
      <article><header><b>02</b><h3>Legacy</h3></header><p>Your wealth, ownership, and family remain exposed to taxes, litigation, support systems, and poor structures.</p><i>→</i><p>Your assets and future are deliberately structured to protect your freedom, family, and bloodline.</p></article>
      <article><header><b>03</b><h3>Law</h3></header><p>You react to allegations, hearings, custody disputes, child support, and an unfamiliar system controlling the stakes.</p><i>→</i><p>You understand the battlefield, build the record, coordinate professionals, and make disciplined strategic decisions.</p></article>
      <article><header><b>04</b><h3>Love</h3></header><p>Conflict, resentment, mistrust, or emotional distance erodes your relationship with your woman and family.</p><i>→</i><p>You lead with truth, boundaries, devotion, and the strength to remain present when pressure rises.</p></article>
    </section>
    <section className="support-choice"><p className="section-kicker">Choose your level of support</p><h2>Which path is right<br /><em>for you?</em></h2><div className="choice-flow"><span>What kind of support do you need?</span><div><article><b>Ongoing brotherhood</b><p>Group coaching, accountability, and a trusted room of capable men.</p><em>Bloodline Brotherhood</em></article><article><b>Private strategy</b><p>Focused counsel when the legal, financial, family, or business stakes are significant.</p><em>Bloodline Advisory</em></article></div></div></section>
    <section className="inner-grid work-list"><article id="brotherhood"><span>Group program</span><h2>Bloodline Brotherhood</h2><p>A private group coaching environment built around Leadership, Legacy, Law, and Love.</p><strong>$497 / month</strong><Link className="button ember" href="/bloodline-brotherhood">View the program</Link></article><article id="advisory"><span>Private advisory</span><h2>Bloodline Advisory</h2><p>For high-net-worth founders, seven-figure entrepreneurs, business owners, and senior leaders navigating consequential battles.</p><strong>Engagements from $15,000</strong><p className="small">Begin with a focused $247 strategy call. The final 15 minutes are reserved to decide whether working together makes sense.</p><Link className="button ink" href="/bloodline-advisory">View the advisory</Link></article></section>
  </div>;
  if (type === "speaking") return <div className="speaking-page"><div className="speaking-lead"><img src="/assets/steve-speaking.jpg" alt="Steve Love speaking to a live audience" /><div><p className="eyebrow dark"><span /> Keynotes · Podcasts · Private Rooms</p><h2>Truth without theater.</h2><p>Steve brings a lived perspective on fatherhood, family systems, leadership under pressure, and what it costs to refuse to disappear.</p><a className="button ink" href="mailto:hello@fathersfront.com?subject=Speaking%20or%20Podcast%20Invitation">Invite Steve</a></div></div><div className="speaking-topics"><article><span>01</span><h3>Fatherhood under fire</h3><p>What happens to families—and society—when fathers are removed, diminished, or forced into permanent conflict.</p></article><article><span>02</span><h3>Leadership in the fight</h3><p>How consequential leaders stay clear, build teams, and keep creating when business and personal battles collide.</p></article><article><span>03</span><h3>Born in blood. Forged in fire.</h3><p>A story of addiction, awakening, international custody litigation, rebuilding, and the refusal to surrender a son.</p></article></div><div className="speaking-cta"><p>Booking Steve for a podcast, keynote, founder community, or private event?</p><a className="button ember" href="mailto:hello@fathersfront.com?subject=Speaking%20or%20Podcast%20Invitation">Start the conversation</a></div></div>;
  if (type === "about") return <AboutTimeline />;
  if (type === "apparel") return <div className="coming-soon"><h2>The Bloodline</h2><p>First drop coming soon.</p><button className="button ink">Get notified</button></div>;
  return <div className="inner-grid editorial-list"><article><span>Law</span><h2>Discipline before reaction.</h2><p>Frameworks for navigating family court, custody, child support, and the systems surrounding them.</p></article><article><span>Leadership</span><h2>Build while it burns.</h2><p>Notes on growing teams, revenue, and leadership capacity when the stakes are personal.</p></article><article><span>Legacy</span><h2>Protect what remains.</h2><p>Wealth, sovereignty, family structure, and the long game beyond the present fight.</p></article></div>;
}

const journey = [
  { number:"01", era:"Age 19", title:"The first calling", text:"I became a father before I had become a man. I did not understand everything fatherhood would demand of me—but from that moment forward, my life was no longer mine alone.", image:"/assets/steve-sons.jpg", align:"right" },
  { number:"02", era:"Fifteen years", title:"The divided man", text:"From the outside, I had built the life I was supposed to want: a wife, children, a home, and a six-figure career. Underneath it, addiction followed me for fifteen years. Achievement could not fill what I refused to face.", align:"left" },
  { number:"03", era:"The awakening", title:"The life behind the life", text:"Eventually, the old identity broke. Recovery was not the finish line. It was the first honest step toward becoming the father my sons deserved.", image:"/assets/steve-hero.jpg", align:"right" },
  { number:"04", era:"The wider world", title:"Freedom, built", text:"I became present with my sons, traveled the world, built businesses, and discovered that freedom is not escape. It is the capacity to create a life you can stand inside without needing to run from it.", image:"/assets/steve-speaking.jpg", align:"left" },
  { number:"05", era:"A new beginning", title:"Love returned", text:"I started a new family. There was a beautiful woman, a home, and a new son. For a moment, everything I had fought to become seemed to have carried me into the life I had imagined.", align:"right" },
  { number:"06", era:"The abduction", title:"The world split open", text:"Then my son was taken across an ocean. In a single act, fatherhood became an international legal battle. The system expected distance, exhaustion, and delay to do what force could not: make me disappear.", align:"left" },
  { number:"07", era:"Two years · Two countries", title:"Learning to litigate", text:"I learned the case down to the smallest fact and fought through courts in Texas and Germany. Every filing, hearing, allegation, and setback became part of a flawless record built around one principle: the best way to beat a lie is with the truth.", image:"/assets/fathers-front-home-hero.jpg", align:"right" },
  { number:"08", era:"Germany", title:"I went to get my son", text:"When the court gave me sole custody, I crossed the ocean to enforce the judgment and bring him home. There was no entourage—just a father who had promised his son he would never stop coming.", align:"left" },
  { number:"09", era:"The return", title:"What comes after the fight", text:"Now it is my son and me, rebuilding daily life while I build the work that came out of the fire. Fathers Front exists for men who still have something to protect, something to lead, and something worth becoming.", image:"/assets/steve-sons.jpg", align:"right" },
];

function AboutTimeline() {
  return <div className="about-journey"><section className="about-prologue"><p className="section-kicker">The origin story</p><h2>A man is not defined by what happens to him.</h2><p>He is defined by what he builds from it. This is the story of being broken open, crossing the fire, and choosing—again and again—not to disappear.</p></section><div className="journey-line" aria-hidden="true" />{journey.map((chapter) => <article className={`journey-chapter journey-${chapter.align}`} key={chapter.number}><div className="journey-marker"><span>{chapter.number}</span></div><div className="journey-copy"><p className="journey-era">{chapter.era}</p><h3>{chapter.title}</h3><p>{chapter.text}</p></div><div className={`journey-visual ${chapter.image ? "has-image" : "is-archive"}`}>{chapter.image ? <img src={chapter.image} alt="" /> : <><span>Archive image</span><b>{chapter.era}</b></>}</div></article>)}<section className="about-epilogue"><p className="journey-era">The next chapter</p><h2>The fight was never the destination.</h2><p>It was the forge. The work now is to restore fatherhood as a foundation of the family—and the family as a foundation of society.</p><Link className="button ink" href="/work-with-steve">Work with Steve</Link></section></div>;
}

export default async function InnerPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const page = pages[slug]; if (!page) notFound();
  return <main><Header /><section className="page-identifier cream-section"><div className="shell"><p className="section-kicker">{page.eyebrow}</p></div></section><section className="inner-content cream-section"><div className="shell"><PageContent type={page.type} /><Link className="text-link dark-link back-home" href="/">← Return home</Link></div></section><Footer /></main>;
}
